spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pizza_project_data
    username: root
    password: 11102002
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    default-property-inclusion: non_null

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"