spring:
  application:
    name: pizza-project-be
  cache:
    type: redis
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379
      password:
      db-default: 0
      timeout: 60000
  jackson:
    default-property-inclusion: non_null
database:
  jdbcUrl : ${DB_URL:jdbc:mysql://localhost:3306/pizza_project_data}
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:11102002}
hikari:
  minimum-idle: 15
  maximum-pool-size: 250
  idle-timeout: 30000
  max-lifetime: 1800000
  connection-test-query: SELECT 1
  pool-name: ApiAppHikariPool
  driverClass: org.mariadb.jdbc.Driver
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"